#!/bin/sh
#
# ufetch-crux - tiny system info for crux

## INFO

# user is already defined
host="$(hostname)"
os="$(crux)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pkginfo -i | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop Enviornment'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop Enviornment'
		WM="${DESKTOP_SESSION}"
	else
		envtype='Window Manager'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='Window Manager'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${cyan}"		# labels
nc="${reset}${bold}${cyan}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${cyan}"			# first color
c1="${reset}${white}"			# second color
c2="${reset}${yellow}"			# third color

## OUTPUT

cat <<EOF

${c0}      ___     ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     (${c1}.· ${c0}|    ${lc}Operating System:        ${ic}${os}${reset}
${c0}     (${c2}<> ${c0}|    ${lc}Linux Kernel:    ${ic}${kernel}${reset}
${c0}    / ${c1}__  ${c0}\\   ${lc}System Uptime:    ${ic}${uptime}${reset}
${c0}   ( ${c1}/  \\ ${c0}/|  ${lc}Installed Packages:  ${ic}${packages}${reset}
${c2}  _${c0}/\\ ${c1}__)${c0}/${c2}_${c0})  ${lc}Shell:     ${ic}${shell}${reset}
${c2}  \/${c0}-____${c2}\/   ${lc}${envtype}:        ${ic}${WM}${reset}

EOF
